// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTIKFqyZHScGsQVrrsRtwIt0_UvJFwqlE',
    appId: '1:785254949728:web:97aa4858dd37678ff53405',
    messagingSenderId: '785254949728',
    projectId: 'delivery-service-98dfc',
    authDomain: 'delivery-service-98dfc.firebaseapp.com',
    storageBucket: 'delivery-service-98dfc.firebasestorage.app',
    measurementId: 'G-E7YJ7K83XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbnYSD2Eh2juMsyO1MEE7kCChWahoXlo8',
    appId: '1:785254949728:android:f0f8eea4a992bb42f53405',
    messagingSenderId: '785254949728',
    projectId: 'delivery-service-98dfc',
    storageBucket: 'delivery-service-98dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpw-Wg5Bn7LmcAjH0Dgr79tuMfg34rtnw',
    appId: '1:785254949728:ios:5ecefaa811c952dff53405',
    messagingSenderId: '785254949728',
    projectId: 'delivery-service-98dfc',
    storageBucket: 'delivery-service-98dfc.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpw-Wg5Bn7LmcAjH0Dgr79tuMfg34rtnw',
    appId: '1:785254949728:ios:5ecefaa811c952dff53405',
    messagingSenderId: '785254949728',
    projectId: 'delivery-service-98dfc',
    storageBucket: 'delivery-service-98dfc.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTIKFqyZHScGsQVrrsRtwIt0_UvJFwqlE',
    appId: '1:785254949728:web:8273e778ef87525af53405',
    messagingSenderId: '785254949728',
    projectId: 'delivery-service-98dfc',
    authDomain: 'delivery-service-98dfc.firebaseapp.com',
    storageBucket: 'delivery-service-98dfc.firebasestorage.app',
    measurementId: 'G-DYHFF42M3L',
  );
}
